DROP DATABASE IF EXISTS car;
CREATE DATABASE car;

USE car;

DROP TABLE IF EXISTS car;

CREATE TABLE IF NOT EXISTS car (
    id_carro INTEGER PRIMARY KEY AUTO_INCREMENT,
    carName VARCHAR(255),
    model VARCHAR(255)
);
